theme: jekyll-theme-tactile
title: Vera Robson Art
description: This site is under construction. Come back soon.
github:
  is_project_page: false
collections:
  artwork:
    output: true
    layout: artwork
    
defaults:
  - scope:
      path: ""
      type: "artwork"
    values:
      layout: "artwork"


navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
