theme: jekyll-theme-tactile
title: Vera Robson Art
description: An artist from Sydney, Australia.
google-site-verification: DksB63YGmZTce2jlqHDH3yddpTWdY8ruI6PzQp4f3sI
    
github:
  is_project_page: false
  
collections:
  artwork:
    output: true
    layout: artwork
    
defaults:
  - scope:
      path: ""
      type: "artwork"
    values:
      layout: "artwork"
